// <auto-generated />
using System;
using CIS174_TestCoreApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CIS174_TestCoreApp.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20201017075552_InitialStudentsCreation")]
    partial class InitialStudentsCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CIS174_TestCoreApp.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId1")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("StudentId1");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstName = "Spencer",
                            Grade = 86,
                            LastName = "Bischoff"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "Rebecca",
                            Grade = 93,
                            LastName = "Lynn"
                        },
                        new
                        {
                            StudentId = 3,
                            FirstName = "James",
                            Grade = 72,
                            LastName = "Rivers"
                        },
                        new
                        {
                            StudentId = 4,
                            FirstName = "Kelly",
                            Grade = 89,
                            LastName = "Ann"
                        },
                        new
                        {
                            StudentId = 5,
                            FirstName = "Jimmy",
                            Grade = 81,
                            LastName = "Lackers"
                        });
                });

            modelBuilder.Entity("CIS174_TestCoreApp.Models.Student", b =>
                {
                    b.HasOne("CIS174_TestCoreApp.Models.Student", null)
                        .WithMany("Students")
                        .HasForeignKey("StudentId1");
                });
#pragma warning restore 612, 618
        }
    }
}
